const actions = {
    SET_GENERAL_STORE: 'SET_GENERAL_STORE',
    SET_DATE: 'SET_DATE',
    SET_SHOW_FORM: 'SET_SHOW_FORM',
    SET_EVENT_FOR_EDIT: 'SET_EVENT_FOR_EDIT',
    SET_ROOM: 'SET_ROOM',
    SET_TIME_START: 'SET_TIME_START',
    SET_TIME_END: 'SET_TIME_END'
};

export default actions;
